admin_facilito/admin_facilito/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home
from .views import error_404

urlpatterns = [
    url(r'^$', home, name = 'home'),
    url(r'^admin/', admin.site.urls),
    url(r'^clients/', include('clients.urls')),
    url(r'^projects/', include('projects.urls')),
]


handler404 = error_404

admin_facilito/clients/urls.py
from django.conf.urls import url
from . import views

app_name = 'client'
urlpatterns = [
    url(r'^show/(?P<username_url>\w+)/$', views.ShowClass.as_view(), name="show"),
    url(r'^login/$', views.LoginClass.as_view(), name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^dashboard/$', views.DashboardClass.as_view(), name="dashboard"),
    url(r'^create/$', views.CreateClass.as_view(), name="create"),
    # url(r'^edit/$', views.EditClass.as_view(), name="edit"),
    url(r'^edit/$', views.edit, name="edit"),
    url(r'^edit/password/$', views.edit_password, name="edit_password"),
    url(r'^edit/social$', views.EditSocialClass.as_view(), name="edit_social"),

]

admin_facilito/clients/models.py
from __future__ import unicode_literals
from django.db import models

from django.contrib.auth.models import User

# Create your models here.
class Client(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE )
    job  = models.CharField(max_length=100, default= "")
    bio  = models.TextField(max_length=200, default= "")

    def __str__(self):
        return self.user.username

class SocialNetwork(models.Model):
    user     = models.OneToOneField(User, on_delete = models.CASCADE )
    facebook = models.URLField(blank=True)
    twitter  = models.URLField(blank=True)
    github   = models.URLField(blank=True)

    def __str__(self):
        return self.user.username

admin_facilito/clients/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from django.contrib.auth.models import User

from .models import Client
from .models import SocialNetwork

'''
Constants
'''
ERROR_MESSAGE_USER = {'required': 'El username es requerido.', 'unique': 'El username ya se encuentra registrado.', 'invalid': 'El username es incorrecto.'}
ERROR_MESSAGE_PASSWORD = {'required': 'Password requerido'}
ERROR_MESSAGE_EMAIL = {'required': 'E-mail requerido', 'invalid':  'Correo electronico no es valido'}


'''
Functions
'''
def must_be_gt(value_password):
    if len(value_password) < 5:
        raise forms.ValidationError('El password debe contener una longitud de 5 como minimo')
    value_password

'''
Class
'''
# Clase para generar el form de un login
class LoginUserForm(forms.Form):
    username = forms.CharField(max_length=20)
    password = forms.CharField(max_length=20, widget = forms.PasswordInput())

    def __init__(self, *args, **kwargs):
        super(LoginUserForm, self).__init__(*args, **kwargs) # Se le dice que siga con su flujo normal despues del override
        # Es para agregarle clases a las etiquetas en el html
        self.fields['username'].widget.attrs.update( {'id': 'username_login', 'class': 'input_login' } )
        self.fields['password'].widget.attrs.update( {'id': 'password_login', 'class': 'input_login' })

class CreateUserForm(forms.ModelForm):

    username = forms.CharField(
        max_length=20,
        error_messages = ERROR_MESSAGE_USER
        )
    password = forms.CharField(
        max_length=20, widget = forms.PasswordInput(),
        error_messages = ERROR_MESSAGE_PASSWORD
        )
    email    = forms.CharField(
        error_messages = ERROR_MESSAGE_EMAIL
        )

    def __init__(self, *args, **kwargs):
		super(CreateUserForm, self).__init__(*args, **kwargs)
		self.fields['username'].widget.attrs.update( {'id': 'username_create' } )
		self.fields['password'].widget.attrs.update( {'id': 'password_create' } )
		self.fields['email'].widget.attrs.update( {'id': 'email_create' } )

    # Nos permite saber si el correo electronico a ingresar ya se ha registrado anteriormente
    # El metodo clean_email se llama cuando se ejecuta el metodo is_valid()
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).count():
            raise forms.ValidationError('El email ingresado ya está registrado en la plataforma')
        return email

    class Meta:
        model = User
        fields = ('username', 'password', 'email')

class EditUserForm(forms.ModelForm):

    username = forms.CharField(
        max_length=20,
        error_messages = ERROR_MESSAGE_USER,
        label = 'Nombre de Usuario'
        )
    email    = forms.CharField(
        error_messages = ERROR_MESSAGE_EMAIL,
        label = 'Correo Electrónico'
        )

    first_name = forms.CharField(label = "Nombre Completo")
    last_name  = forms.CharField(label = "Apellido")

    class Meta:
        model  = User
        fields = ('username', 'email', 'first_name', 'last_name')

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.filter(email=email).exclude(pk = self.instance.id).count():
            raise forms.ValidationError('El email ingresado ya está registrado en la plataforma')
        return email

# El atributo validators se utiliza para encapsular las funciones que se deben de utilizar para validar los campos
class EditPasswordForm(forms.Form):
    # Obtiene los campos del formulario para cambiar la contrasena
    password        = forms.CharField(max_length=20, widget = forms.PasswordInput(), error_messages = ERROR_MESSAGE_PASSWORD)
    new_password    = forms.CharField(max_length=20, widget = forms.PasswordInput(), error_messages = ERROR_MESSAGE_PASSWORD, validators = [must_be_gt])
    repeat_password = forms.CharField(max_length=20, widget = forms.PasswordInput(), error_messages = ERROR_MESSAGE_PASSWORD, validators = [must_be_gt])

    # Metodo que se llama cuando se realiza el form.is_valid dentro de la vista
    def clean(self):
        clean_data = super(EditPasswordForm, self).clean()
        password1  = clean_data.get('new_password')
        password2  = clean_data.get('repeat_password')

        if password1 != password2:
            raise forms.ValidationError('El nuevo password no es el mismo que el de validacion')

class EditClientForm(forms.ModelForm):

    job = forms.CharField(label = "Trabajo actual", required=False)
    bio = forms.CharField(label = "Biografía", widget = forms.Textarea, required=False)

    class Meta:
        model   = Client
        # fields = ['', ''] -- Los que quiero que esten.
        exclude = ['user'] # Excluye los campos que se encuentren aqui del modelo

    def __init__(self, *args, **kwargs):
        super(EditClientForm, self).__init__(*args, **kwargs)
        self.fields['job'].widget.attrs.update({'id': 'job_edit_client', 'class': 'validate'})
        self.fields['job'].widget.attrs.update({'id': 'bio_edit_client', 'class': 'validate'})

class EditClientSocial(forms.ModelForm):
    class Meta:
        model   = SocialNetwork
        exclude = ['user']

admin_facilito/clients/views.py
from django.shortcuts import render, redirect

from django.http import HttpResponse, HttpResponseRedirect

from .models import Client, SocialNetwork

from forms import LoginUserForm
from forms import CreateUserForm
from forms import EditUserForm
from forms import EditPasswordForm
from forms import EditClientForm
from forms import EditClientSocial

from django.contrib import messages
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.models import User

from django.contrib.auth import authenticate
from django.contrib.auth import login as login_django
from django.contrib.auth import logout as logout_django
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required

from django.views.generic import View, DetailView, CreateView
from django.views.generic.edit import UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.urlresolvers import reverse_lazy



'''
Class
'''

class ShowClass(DetailView):
    model           = User
    template_name   = 'client/show.html'
    slug_field      = 'username'  #Campo de la base de datos por el que se va a traer la info
    slug_url_kwarg  = 'username_url' #Como se llama en la url.


class LoginClass(View):
    form     = LoginUserForm()
    message  = None
    template = 'client/login.html'

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated():
            return redirect('client:dashboard')
        return render(request, self.template, self.get_context())

    def post(self, request, *args, **kwargs):
        username_post = request.POST['username']
        password_post = request.POST['password']

        # Se verifica si el usuario y contasena mandado existen dentro de la base de datos.
        user = authenticate(username=username_post, password=password_post)
        if user is not None:
            login_django(request, user)
            return redirect('client:dashboard')
        else:
            message = "Username o password incorrectos"
        return render(request, self.template, self.get_context())

    # Funcion para obtener el contexto
    def get_context(self):
        return {'form': self.form, 'message': self.message}
'''
def login_con_funcion(request):
    # Primero verifica que en caso de que el usuario este
    # logueado, lo regresa a la ventana de dashboard
    if request.user.is_authenticated():
        return redirect('client:dashboard')

    # Si nos estan enviando el formulario .:.
    message = None
    if request.method == 'POST':
        username_post = request.POST['username']
        password_post = request.POST['password']

        # Se verifica si el usuario y contasena mandado existen dentro de la base de datos.
        user = authenticate(username=username_post, password=password_post)
        if user is not None:
            login_django(request, user)
            return redirect('client:dashboard')
        else:
            message = "Username o password incorrectos"

    form = LoginForm()
    context = {
        'form': form,
        'message': message
    }
    return render(request, 'login.html', context)
'''


class DashboardClass(LoginRequiredMixin, View):
    login_url = 'client:login'

    def get(self, request, *args, **kwargs):
        return render(request, 'client/dashboard.html', {})
'''
# El login_required es para ingresar a la pagina unicamente si esta loggeado
@login_required( login_url = 'client:login') # Si no esta loggeado, lo manda a la de login.
def dashboard_function(request):
    # if request.user.is_authenticate()
    return render(request, 'dashboard.html', {})
'''


class CreateClass(CreateView):
    success_url   = reverse_lazy('client:login') #reverse_lazy regresa toda la url de client:login
    model         = User
    template_name = 'client/create.html'
    form_class    = CreateUserForm

    # Se sobreescribe form_valid para la encriptacion del password
    def form_valid(self, form):
        self.object = form.save( commit = False )
        self.object.set_password( self.object.password )
        self.object.save()
        return HttpResponseRedirect( self.get_success_url() ) #REcupera la url de exito -- success_url   = 'client:login'


'''
def create(request):

    form = CreateUserForm(request.POST or None)  # El Request.POST permite poner la logica desde en la clase Forms y no en la View
    if request.method == 'POST':
        if form.is_valid():
            # Es en caso de que el password se muestre cuando se crea la cuenta.
            # Para guardar correctamente en la BD.
            user = form.save( commit = False )
            user.set_password( user.password )
            user.save()
            return redirect('client:login')

    context = {
        'form' : form
    }
    return render(request, 'create.html', context)
'''

'''
class EditClass(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    login_url = 'client:login'
    model = User
    template_name = 'client/edit.html'
    success_url   = reverse_lazy('client:edit')
    form_class    = EditUserForm
    success_message = "Tu usuario ha sido actualizado"

    # El metodo form_valid se llama cuando el formulario es valido
    # Se sobreescribe para la personalizacion con los messages
    def form_valid(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        #Se le dice que siga con el flujo normal despues de haber ejecutado nuestra validacion
        return super(EditClass, self).form_valid(request, *args, **kwargs)

    def get_object(self, queryset = None):
        return self.request.user
'''

# LoginRequiredMixin se utiliza para validar que el usuario esta loggeado
class EditSocialClass(LoginRequiredMixin, UpdateView, SuccessMessageMixin):
    login_url     = 'client:login'
    model         = SocialNetwork
    template_name = 'client/edit_social.html'
    success_url   = reverse_lazy('client:edit_social')
    form_class    = EditClientSocial
    success_message = "Tus usuarios han sifo actualizados exitosamente"

    def get_object(self, queryset = None):
        return self.get_social_instance()

    def get_social_instance(self):
        try:
            return self.request.user.socialnetwork
        except:
            return SocialNetwork(user = self.request.user)

'''
Functions
'''
@login_required( login_url = 'client:login')
def edit_password(request):
    # En caso de que sea una solicitud POST, dentro de form se recuperan todos los datos del formulario.
    form = EditPasswordForm(request.POST or None)

    # Si es una solicitud POSt, se valida que la informacion es correcta
    if request.method == 'POST':
        if form.is_valid():
            current_password = form.cleaned_data['password'] # Obtiene los valores de la forma
            new_password = form.cleaned_data['new_password']

            # Despues de validar que la contrasena (formato) es valida, se verifica si la contrasena corresponde al usuario actual.
            if authenticate(username = request.user.username, password = current_password):
                request.user.set_password( new_password ) # Si si, se le actualiza la nueva contrasena
                request.user.save()
                # Se utiliza para continuar al usuario en su sesion
                update_session_auth_hash(request, request.user)
                messages.success(request, 'Password actualizado, messages')
            else:
                messages.error(request, "Password invalido. No corresponde al usuario %s" %(request.user.username))


    context = {'form' : form, }
    return render(request, 'client/edit_password.html', context)

@login_required( login_url = 'client:login')
def logout(request):
    logout_django(request)
    return redirect('client:login')

@login_required( login_url = 'client:login')
def edit(request):
    form_client = EditClientForm(request.POST or None, instance = client_instance(request.user) )  # Rellena los campos con lo que existe actualmente dentro de la BD
    form_user   = EditUserForm(request.POST or None, instance = request.user)
    if request.method == 'POST':
        if form_client.is_valid() and form_user.is_valid():
            form_user.save()
            form_client.save()
            messages.success(request, 'Datos actualizados correctamente')

    context = {
        'form_client': form_client,
        'form_user'  : form_user
    }
    return render(request, 'client/edit.html', context)

def client_instance(user):
    try:
        return user.client
    except:
        return Client(user = user)

admin_facilito/templates/client/create.html
{% extends 'bases/base_admin.html' %}

{% block title %} Admin facilito {% endblock %}

{% block scripts %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" />

{% endblock %}

{% block content %}

	<div class= "class_container_form">
		<form method="post" action="">
			{% csrf_token %}

			  {# {{ form.as_p }} #}

			  {% for field in form %}

			  	<div class="row" >
			  		<div class="input-field col s12">

			  			{% if field.errors %}
			  				{{ field.errors }}
			  			{% endif %}

			  			{{ field }}
			  			<label class="{% for class in field.label_clasess %} {{ class }} {% endfor %}" for="{{ field.name }}" >  {{ field.label }} </label>
			  		</div>
			  	</div>

			  {%  endfor %}

			<input class="btn #9e9e9e grey" type="submit" value="registro">
		</form>
	</div>

{% endblock %}

{% block footer %}
	<footer>
		<p> Ya cuento con una  <a href="{% url 'client:login' %}"> cuenta	</a></p>
	</footer>
{% endblock %}

admin_facilito/templates/client/dashboard.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Dashboard {% endblock %}

{% block scripts %}
	{# nada por el momento #}
{% endblock %}


{% block content %}
	<h3>Bienvenido {{ user.username|title }}</h3>
	<a href="{% url 'client:show' user.username %}">  {{user.username}} </a>
{% endblock %}

{% block footer %} {% endblock %}

admin_facilito/templates/client/edit.html
{% extends 'client/bases/edit_base.html' %}

{% block title %} Editar cuenta {% endblock %}

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" />
{% endblock %}

{% block content %}
	<div class="collection">
		<a href="{% url 'client:edit' %}" class="collection-item active">Perfil</a>
		<a href="{% url 'client:edit_password' %}" class="collection-item">Password</a>
		<a href="{% url 'client:edit_social' %}" class="collection-item">Redes Sociales</a>
	</div>

	<div class = "class_container_form" >
		<form method="post" action="">
			{% csrf_token %}

      {% include "includes/_forms.html" with form=form_user %}
      {% include "includes/_forms.html" with form=form_client %}

      <input class="btn #9e9e9e grey" type="submit" value="Actualizar">
		</form>
	</div>

{% endblock %}

{% block footer %} {% endblock %}

admin_facilito/templates/client/edit_password.html
<!-- Se refiere al html base que va a utilizar -->
{% extends 'client/bases/edit_base.html' %}

{% block title %}
  Editar Usuario
{% endblock %}

{% block subtitle %}
  Editar Usuario
{% endblock %}

{% block content %}
  <div class="collection">
    <a href="{% url 'client:edit' %}" class="collection-item">Perfil</a>
    <a href="{% url 'client:edit_password' %}" class="collection-item active">Password</a>
    <a href="{% url 'client:edit_social' %}" class="collection-item ">Redes Sociales</a>
  </div>
  <form method = "post" action="">
      {% csrf_token %}
      {{ form.as_p }}
      <input type="submit" value="Actualizar password">
  </form>
{% endblock %}

admin_facilito/templates/client/edit_social.html
{% extends 'client/bases/edit_base.html' %}

{% block title %} Editar redes sociales {% endblock %}

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" />
{% endblock %}

{% block content %}
  <div class="collection">
    <a href="{% url 'client:edit' %}" class="collection-item">Perfil</a>
    <a href="{% url 'client:edit_password' %}" class="collection-item">Password</a>
    <a href="{% url 'client:edit_social' %}" class="collection-item active">Redes Sociales</a>
  </div>
	<div class = "class_container_form" >
		<form method="post" action="">
			{% csrf_token %}
			{% include "includes/_forms.html" with form=form only %}
			<input class="btn #9e9e9e grey" type="submit" value="actualizar">
		</form>
	</div>
{% endblock %}

{% block footer %}

{% endblock %}

admin_facilito/templates/client/login.html
{% extends 'bases/base_admin.html' %}

{% block title %} Admin facilito {% endblock %}

{% block scripts %}
	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" />

{% endblock %}

{% block content %}

	<div class= "class_container_form">
		<form method="post" action="">
			{% csrf_token %}

			  {# {{ form.as_p }} #}

			  {% for field in form %}

			  	<div class="row" >
			  		<div class="input-field col s12">

			  			{% if field.errors %}
			  				{{ field.errors }}
			  			{% endif %}

			  			{{ field }}

			  			<label class="{% for class in field.label_clasess %} {{ class }} {% endfor %}" for="{{ field.name }}" >  {{ field.label }} </label>


			  		</div>
			  	</div>

			  {%  endfor %}

			<input class="btn #9e9e9e grey" type="submit" value="ingreso">
		</form>
	</div>

{% endblock %}

{% block footer %}

	<footer>
  	<a href="#"> Olvide mi contraseña  </a>
		<p> Crea una nueva cuenta <a href="{% url 'client:create' %}"> aqui </a></p>
	</footer>

{% endblock %}

admin_facilito/templates/client/show.html
{% load client_extras %}

<html>
  <head>
  	<meta charset="UTF-8">
  	<title> {{ user.username }}</title>
  </head>
  <body>

  	<h3>Hola Usuario  {{ user.username|title }}  </h3>
  	<p>Biografía </p>
  	<p> {{user.client.bio|truncatechars:100  }} </p>

    {% if user.socialnetwork %}
    	{% for field in user.socialnetwork|list_fields %}
    		{% with user.socialnetwork|get_value:field as value %}

    			{% if value %}
    				<p> {{ field }} </p>
    				<p> {{ value }} </p>
    			{% endif %}

    		{% endwith %}
    	{% endfor %}
    {% endif %}

  </body>
</html>