admin_facilito/admin_facilito/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home
from .views import error_404

urlpatterns = [
    url(r'^$', home, name = 'home'),
    url(r'^admin/', admin.site.urls),
    url(r'^clients/', include('clients.urls')),
    url(r'^projects/', include('projects.urls')),
]


handler404 = error_404

admin_facilito/clients/urls.py
from django.conf.urls import url
from . import views

app_name = 'client'
urlpatterns = [
    url(r'^show/(?P<username_url>\w+)/$', views.ShowClass.as_view(), name="show"),
    url(r'^login/$', views.LoginClass.as_view(), name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^dashboard/$', views.DashboardClass.as_view(), name="dashboard"),
    url(r'^create/$', views.CreateClass.as_view(), name="create"),
    # url(r'^edit/$', views.EditClass.as_view(), name="edit"),
    url(r'^edit/$', views.edit, name="edit"),
    url(r'^edit/password/$', views.edit_password, name="edit_password"),
    url(r'^edit/social$', views.EditSocialClass.as_view(), name="edit_social"),

]

admin_facilito/templates/bases/base_admin.html
{% load staticfiles %}
<!DOCTYPE htlm>
<html>
  <head>
  	<meta charset="UTF-8">

  	<title> {% block title %} {% endblock %} </title>

  		<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/css/materialize.min.css">

      <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.3/js/materialize.min.js"></script>

      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}" />

     {% block scripts %} {% endblock %}

  </head>
  <body>

  	<header>
  	  <div class="navbar-fixed">
  	    <nav>
  	      <div class="nav-wrapper #9e9e9e grey">
  	      	<a href="{% url 'home' %}" class="brand-logo">Admin Facilito</a>
  	        <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
  	        <ul class="right hide-on-med-and-down lighten-2">
  	          <li><a href="{% url 'client:login' %}">Login</a></li>
  	          <li><a href="{% url 'client:create' %}">Registro</a></li>
  	        </ul>
  	        <ul class="side-nav" id="mobile-demo">
  	          <li><a href="{% url 'client:login' %}">Login</a></li>
  	          <li><a href="{% url 'client:create' %}">Registro</a></li>
  	        </ul>
  	      </div>
  	    </nav>
  	   </div>
  	</header>


  	{% if messages %}
  		<div class="center-align">
  			<ul class="messages">
  	    	{% for message in messages %}
  	    		<li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
  	    	{% endfor %}
  			</ul>
  		</div>
  	{% endif %}

  	{% block content %} {% endblock %}

  	{% block footer %} {% endblock %}

  </body>
</html>