admin_facilito/admin_facilito/urls.py
from django.conf.urls import url, include
from django.contrib import admin

from .views import home
from .views import error_404

urlpatterns = [
    url(r'^$', home, name = 'home'),
    url(r'^admin/', admin.site.urls),
    url(r'^clients/', include('clients.urls')),
    url(r'^projects/', include('projects.urls')),
]


handler404 = error_404

admin_facilito/clients/urls.py
from django.conf.urls import url
from . import views

app_name = 'client'
urlpatterns = [
    url(r'^show/(?P<username_url>\w+)/$', views.ShowClass.as_view(), name="show"),
    url(r'^login/$', views.LoginClass.as_view(), name="login"),
    url(r'^logout/$', views.logout, name="logout"),
    url(r'^dashboard/$', views.DashboardClass.as_view(), name="dashboard"),
    url(r'^create/$', views.CreateClass.as_view(), name="create"),
    # url(r'^edit/$', views.EditClass.as_view(), name="edit"),
    url(r'^edit/$', views.edit, name="edit"),
    url(r'^edit/password/$', views.edit_password, name="edit_password"),
    url(r'^edit/social$', views.EditSocialClass.as_view(), name="edit_social"),

]

admin_facilito/projects/urls.py
from django.conf.urls import url
from . import views

app_name = 'project'
urlpatterns = [
    url(r'^create/$', views.CreateClass.as_view(), name="create"),
    url(r'^my_projects/$', views.ListClass.as_view(), name="my_projects"),
    url(r'^show/(?P<slug>[\w-]+)/$', views.ShowClass.as_view(), name="show"),
    url(r'^edit/(?P<slug>[\w-]+)/$', views.edit, name="edit"),
]

admin_facilito/projects/models.py
from __future__ import unicode_literals

from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models

from status.models import Status
from django.utils import timezone

import datetime

# Create your models here.


class Project(models.Model):
    user        = models.ForeignKey(User, on_delete= models.CASCADE)
    title       = models.CharField(max_length=50)
    description = models.TextField()
    dead_line   = models.DateField()
    create_date = models.DateField(default = datetime.date.today)
    slug        = models.CharField(max_length=50, default = "")  # Campo que se utiliza para obtener el registro de la base de datos

    def __str__(self):
        return self.title

    def validate_unique(self, exclude=None):
        self.slug = self.create_slug_field(self.title)
        if Project.objects.filter(slug = self.slug).exclude(pk = self.id).exists():
            raise ValidationError('Un proyecto con el mismo titulo ya se encuentra registrado')

    def create_slug_field(self, value):
        return value.lower().replace(" ", "-")


class ProjectStatus(models.Model):
    Project = models.ForeignKey(Project)
    status = models.ForeignKey(Status)
    create_date = models.DateTimeField(default=timezone.now)

admin_facilito/projects/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from django import forms
from .models import Project

import datetime

class ProjectForm(forms.ModelForm):
    title = forms.CharField(label = 'Titulo', required = True)
    description = forms.CharField(label = 'Descripción', required = True, widget=forms.Textarea)
    dead_line = forms.DateField(initial=datetime.date.today)

    class Meta:
        model = Project
        fields = ('title', 'description', 'dead_line')

admin_facilito/projects/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404

from django.views.generic import CreateView, ListView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin  # Valida si el usuario esta loggeado
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse_lazy
from django.contrib.auth.decorators import login_required

from status.models import Status
from .models import Project

from .forms import ProjectForm

# Create your views here.


class CreateClass(LoginRequiredMixin, CreateView):
    login_url     = 'client:login'
    template_name = 'project/create.html'
    model         = Project
    form_class    = ProjectForm

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        self.object.projectstatus_set.create(status=Status.get_default_status())
        return HttpResponseRedirect(self.get_url_project())

    def get_url_project(self):
        return reverse_lazy('project:show', kwargs={'slug': self.object.slug})


# Clase utilizada para Listar los proyectos creados por el usuario actual


class ListClass(LoginRequiredMixin, ListView):
    login_url     = 'client:login'
    template_name = 'project/own.html'

    # Query que define los registros que se trae a traves del filter de la tabla Project
    def get_queryset(self):
        return Project.objects.filter(user=self.request.user).order_by('dead_line')


class ShowClass(LoginRequiredMixin, DetailView):
    login_url       = 'client:login'
    model           = Project
    template_name   = 'project/show.html'


"""
Functions
"""


@login_required(login_url='client:login')
def edit(request, slug=''):
    project = get_object_or_404(Project, slug=slug)
    form_project = ProjectForm(request.POST or None, instance=project)
    context = {
        'form_project': form_project
    }
    return render(request, 'project/edit.html', context)
    

admin_facilito/templates/project/create.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Nuevo Proyecto {% endblock %}

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" />
{% endblock %}

{% block content %}
	<div class = "class_container_form" >
		<form method="post" action="">
			{% csrf_token %}
			{% include "includes/_forms.html" with form=form only %}
			<input class="btn #9e9e9e grey" type="submit" value="crear">
		</form>
	</div>
{% endblock %}

{% block footer %}

{% endblock %}

admin_facilito/templates/project/edit.html
{% extends 'client/bases/edit_base.html' %}

{% block title %} Editar Proyecto {% endblock %}

{% block scripts %}
    {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css'%}">
{% endblock %}

{% block content %}
    <div class="class_container_form">
        <form method="post" action="">
            {% csrf_token %}
            {% include "includes/_forms.html" with form=form_project only %}
            <input class="btn #9e9e9e grey" type="submit" name="Actualizar">
        </form>
    </div>
{% endblock %}

{% block footer %}
{% endblock %}

admin_facilito/templates/project/own.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} Mis Proyectos {% endblock %}

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" />
{% endblock %}

{% block content %}
	<a href="{% url 'project:create' %}"> Crear proyecto</a>

	{% for project in object_list %}
    <p> {{ project.title }} </p>
	{% endfor %}

{% endblock %}

{% block footer %}

{% endblock %}

admin_facilito/templates/project/show.html
{% extends 'client/bases/edit_base.html'%}

{% block title %} {{ project.title }} {% endblock %}

{% block scripts %}
	{% load staticfiles %}
	 <link rel="stylesheet" type="text/css" href="{% static 'css/forms.css' %}" />
{% endblock %}

{% block content %}

	<h4>{{ project.title }}</h4>

{% endblock %}

{% block footer %}

{% endblock %}